### ISSUE TITLE
Deploy to final host machine

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-datahub#194]
**Problem:**
The datahub needs to be deployed to the new host machine once it is set up in the in the display room by @pclemow

**Proposed Solution:**
Installed on the machine:
- Docker

Then this should be deployed using [our standard web server setup](https://github.com/ImperialCollegeLondon/rse-webapp-deployment) - ideally copying the version in the current VM at `/opt/deployment/gridlington/gridlington-datahub`

**Additional context:**
- It might be required to change the ports used by this to 4443 and 8000 (instead of 443 and 80) depending on how the OpenVidu server is deployed.
- The IP address will need to be shared with Jacek and Yue so they can update the urls they interact with from the model side.

**Comment by dalonsoa** [comment]
This will be tackled when there is a need for it, as the Agents and Opal data and simulation runs seem to need re-doing with more data, pending on a conversation between @pclemow , Jacek and Yue (and us) in January.

**Comment by AdrianDAlessandro** [comment]
Currently OpenVidu (for WebRTC) is not installed - @pclemow is this still needed/desired?

**Comment by AdrianDAlessandro** [comment]
Datahub is now running on the host machine.
