### ISSUE TITLE
There is no way to reset the data

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-datahub#222]
**Problem:**
There is currently no way to reset the data remotely. There is an existing function, `reset_data` in `data.py` but it is not used by any of the existing API endpoints.

**Proposed Solution:**
Either create a standalone endpoint for resetting the data (ie for restarting the simulation) and/or use the existing `/model_ready` endpoint to reset the data, assuming the model_ready signal will only be sent when the model is reset.

**Comment by AdrianDAlessandro** [comment]
@pclemow the solution for this this depends on the behaviour you want when pressing the buttons on the controller

**Comment by pclemow** [comment]
I am not sure on the implications of this? 

Are we talking recorded or live data?

For recorded data it would be good to be able to reset it whenever I want, I believe this can be achieved through a refresh though?

For life data  I suspect you cannot simply "reset" partway through and actually need to stop, reload and restart. Yue would be able to answer (I dont know his username to tag him.)

**Comment by AdrianDAlessandro** [comment]
This is for the Data Hub specifically, so it's only relevant for live model data.

@yuezhu71 is currently working on allowing the Opal model to be stopped and restarted. Once that is complete, the way the datahub will behave is to add the data from the new model run on top of the old model run instead of wiping the old data and restarting.

I think you and Yue should decide together what behaviour makes the most sense for the datahub from both ends (ie from the vis system controller and from the opal model). Options I can see:
- Data Hub always resets itself at the start of a model run
- Data Hub will reset itself whenever the `/model_ready` endpoint is used. The Opal model will use this endpoint after it has been stopped and completed resetting itself.
- Data Hub provides a standalone endpoint (that can be used directly) to wipe/reset the data (this is the most complicated)
