### ISSUE TITLE
Description of data model

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-datahub#4]
**Problem:**
The data model will form the heart of the DataHub, the way this is structured needs to be determined before it can be implemented in code.

**Proposed Solution:**
The details of it will require input from researchers and also viewing https://github.com/yuezhu71/IDLES_python

The non-code description of the data model (variable names, format they will come in, etc) should be put into [the Wiki for this repo](https://github.com/ImperialCollegeLondon/gridlington-datahub/wiki)

Initial ideas:
- 3 separate data objects for the most raw form of the data from each model (WESIM, OPAL-RT & Agents)
- 1 object that groups all of these together into a format that is visualisation-friendly

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-141-3

**Comment by CWestICL** [comment]
I've updated the [Opal data page](https://github.com/ImperialCollegeLondon/gridlington-datahub/wiki/Opal-data) and written up a first draft of the [Agent model data page](https://github.com/ImperialCollegeLondon/gridlington-datahub/wiki/Agent-model-data) if someone wants to take a look!

**Comment by AdrianDAlessandro** [comment]
I must look through Jacek's email with feedback for the [Agent model data page](https://github.com/ImperialCollegeLondon/gridlington-datahub/wiki/Agent-model-data)
