### ISSUE TITLE
Implement I/O Functionality for the Data Model

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-datahub#6]
**Problem:**
Once the data model is defined and implemented in code #5 the infrastructure around continually running the datahub and providing input and output functionality must be implemented.

**Proposed Solution:**
Set up a continually running process that manages the I/O for the data hub (input from models and output to vis system) and/or holds the data in memory. This process will be:
- [x] The python process running [FastAPI](https://fastapi.tiangolo.com/) (which will be used for the #3)

The above decision will be influenced by the decision made in #5 about whether to host the data in memory or in a database.

**Comment by CWestICL** [comment]
I've had a play-around with FastAPI and have been able to run a web server that can I/O data held in memory. 

The following is some of the contents of `main.py`:
```
from fastapi import FastAPI

app = FastAPI()


@app.get("/item", tags=['items'])
async def get_items() -> dict:
    return {"Data": items}


@app.post("/item", tags=["items"])
async def add_item(item: dict) -> dict:
    items.append(item)
    return {
        "data": "A item is Added!"
    }


items = [
    {
        "id": 0,
        "name": "Keyboard"
    },
    {
        "id": 1,
        "name": "Mouse"
    }
]
```
The server can then be run with the following command:
`uvicorn main:app --reload`
While the server is running, I've been able to GET the list of dicts from the `items` variable, POST a new dict to the list and then GET the list again with the new dict persisting. So if the size and nature of the incoming data allows, we should be able to hold it in memory this way.
